### ISSUE TITLE
Video stream picture is unclear, with mosaic-like squares

### ISSUE THREAD

**Issue by unijiang** [OpenIPC/builder#20]
It looks like a regression in my device, this behavior started in March. The stream quality is good before.

Device: t31_lite_xiaomi-mjsxj03hl-nor

![blur](https://github.com/OpenIPC/builder/assets/16097705/65c6b74a-bce8-4cbb-9c59-deed8c599261)
![clear](https://github.com/OpenIPC/builder/assets/16097705/817201b0-a432-4102-8a8b-fb4b490c2c9b)

```yaml
system:
  webAdmin: enabled
  buffer: 1024
image:
  mirror: true
  flip: true
  rotate: none
  contrast: 50
  hue: 50
  saturation: 50
  luminance: 50
osd:
  enabled: false
  template: "%Y-%m-%d %H:%M:%S"
  posX: 16
  posY: 16
nightMode:
  enabled: true
  irSensorPinInvert: false
  irCutSingleInvert: false
  irCutPin1: 49
  irCutPin2: 50
  backlightPin: 60
  maxThreshold: 100
  minThreshold: 50
records:
  enabled: false
  path: /mnt/mmcblk0p1/%F/%H.mp4
  maxUsage: 95
video0:
  enabled: true
  codec: h264
  size: 2304x1296
video1:
  enabled: false
  codec: h264
  size: 640x360
jpeg:
  enabled: true
mjpeg:
  size: 640x360
  fps: 5
  bitrate: 1024
audio:
  enabled: true
  volume: 40
  srate: 8000
  speakerPinInvert: false
  outputEnabled: false
  codec: aac
rtsp:
  enabled: true
  port: 554
hls:
  enabled: false
youtube:
  enabled: false
motionDetect:
  enabled: false
  visualize: false
  debug: false
ipeye:
  enabled: false
watchdog:
  enabled: true
  timeout: 300
onvif:
  enabled: false
isp:
  blkCnt: 1
```
